// src/components/ViewCell.svelte
<script lang="ts">
    import { marked } from "marked";
    import { run, type Entry } from "@ligature/ligature";

    export let source: string;
    export let output: string;
    export let type: "markdown" | "wander";

    function printResult(result: Entry[]): string {
        let res = "{\n"
        for (let entry of result) {
            if (entry.type == "extension") {
                res += "  " + entry.element.symbol + " : " + entry.concept.symbol + ",\n"
            } else if (entry.type == "nonextension") {
                res += "  " + entry.element.symbol + " :¬ " + entry.element.symbol + ",\n"
            } else {
                res += "  " + entry.first.symbol + " " + entry.role.symbol + " " + entry.second.symbol + ",\n"
            }
        }
        return res + "}"
    }
</script>

<div class="cell">
    {#if source == ""}
        <div><em>Empty Cell</em></div>
    {:else}
        {#if type == "markdown"}
            <div>{@html marked.parse(source)}</div>
        {:else}
            <div><pre><code>{printResult(run(source))}</code></pre></div>
        {/if}
    {/if}
</div>

<style>

</style>

// src/components/ViewCell.tsx
import { marked } from "marked";
import { run } from "@ligature/ligature";
import { Match, Switch } from "solid-js";
import { printNetwork } from "@ligature/ligature-components/src/text/text"
import { ssr } from "solid-js/web";

// export let source: string;
// export let output: string;
// export let type: "markdown" | "wander";

export function ViewCell(props: any) {
    return <div class="cell">
        <Switch>
            <Match when={props.source == "" || props.source == undefined || props.source == null}>
                <div><em>Empty Cell</em></div>
            </Match>
            <Match when={props.source != ""}>
                <Switch>
                    <Match when={props.type == "wander"}>
                        <div>{ssr(marked.parse(props.source))}</div>
                    </Match>
                    <Match when={props.type == "markdown"}>
                        <div><pre><code>{printNetwork(run(props.source))}</code></pre></div>                    
                    </Match>
                </Switch>
            </Match>
        </Switch>
    </div>
}
